# Generated by Django 3.2.9 on 2021-11-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='iniciales',
            field=models.CharField(max_length=20, verbose_name='Iniciales'),
        ),
    ]
