# Generated by Django 3.2.9 on 2021-11-28 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_alter_departamento_iniciales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'verbose_name_plural': 'Areas'},
        ),
    ]
