# Generated by Django 3.2.9 on 2021-11-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50, verbose_name='Skills')),
            ],
            options={
                'verbose_name_plural': 'Skill',
            },
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name_plural': 'Workers'},
        ),
    ]
