# Generated by Django 3.2.9 on 2021-11-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20211128_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='skills',
            field=models.ManyToManyField(to='persona.Skills'),
        ),
    ]
